
---
spring:
  config.activate.on-profile: default
  sql.init.platform: h2
cds:
  data-source.auto-config.enabled: false
  security:
    mock:
      users:
        - name: viewer
          roles:
            - Viewer

        - name: admin
          roles:
            - Admin

---
spring:
  config.activate.on-profile: cloud
cds:
  index-page.enabled: true
  data:
    db:
      vcapp: true
  security.mock.enabled: true	
  security:
    mock:
      users:
        - name: viewer
          roles:
            - viewer

        - name: admin
          roles:
            - admin
            
---
management:
  endpoint:
    health:
      show-components: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
  health:
    defaults:
      enabled: false
    ping:
      enabled: true
    db:
      enabled: true
---
spring:
  profiles:
    active:
    - cloud